/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.5
 * Generated at: 2019-06-18 05:22:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;

public final class Hotfid_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/TopWrapper.jsp", Long.valueOf(1560767190608L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1558674977795L));
    _jspx_dependants.put("/fullView.jsp", Long.valueOf(1560828925457L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>이번달 인기음식</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"HotTipStyle.css\" >\r\n");
      out.write("<script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\".open-fullview\").click(function() {\r\n");
      out.write("\t\t\t$(\"#dim-layer\").css(\"display\", \"block\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".close-fullview\").click(function() {\r\n");
      out.write("\t\t\t$(\"#dim-layer\").css(\"display\", \"none\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Top -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"TopWrapperStyle.css\" >\r\n");

	//로그인 한 사람이라면 userID라는 변수에 해당 아이디가 담기고 그렇지 않으면 null값
	String userid = null;
	if (session.getAttribute("username") != null) {
		userid = (String) session.getAttribute("username");
	}
	
	Connection con = null;
	PreparedStatement pstmt = null;
	ResultSet rs = null;
	
	String driver = "com.mysql.jdbc.Driver";
	String url = "jdbc:mysql://localhost:3306/mucktip?serverTimezone=UTC&useSSL=false";
	String id = "root";
	String pw = "alflarhkgkrrh1!";

      out.write("\r\n");
      out.write("<!-- 맨위에 top메뉴 공간 개발 나중에 따로 빼놓을 부분-->\r\n");
      out.write("\t\t<nav id=\"top-menu-all\">\r\n");
      out.write("\t\t<div id=\"main-menu\">\r\n");
      out.write("\t\t\t<div class=\"contents-wrapper\">\r\n");
      out.write("\t\t\t\t<div class=\"left-contents-wrapper\">\r\n");
      out.write("\t\t\t\t\t<div class=\"muktip-logo\"></div>\r\n");
      out.write("\t\t\t\t\t<a href=\"firstPage.jsp\" class=\"new-tip\">최신 먹팁</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"recommendTip.jsp\" class=\"good\">추천</a>\r\n");
      out.write("\t\t\t\t</div><!-- left-contents-wrapper -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"right-contents-wrapper\">\r\n");
      out.write("\t\t\t\t\t");

						//로그인이 안된 경우
						if (userid == null) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"login-join\"> <!-- 로그인 / 가입 -->\r\n");
      out.write("\t\t\t\t\t\t<a href=\"login.jsp\">로그인</a> /\r\n");
      out.write("\t\t\t\t\t\t<a href=\"join.jsp\">가입</a> <!-- 가입 페이지 미구현 -->\r\n");
      out.write("\t\t\t\t\t</div> <!-- login-join -->\r\n");
      out.write("\t\t\t\t\t");

						} else { //로그인이 된 경우
							
							try {
								Class.forName(driver);
								con = DriverManager.getConnection(url, id, pw);
								
								pstmt = con.prepareStatement("select * from user where id =?");
								pstmt.setString(1, userid);
								rs = pstmt.executeQuery();
								
								if(rs.next()) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"user-menu\" id=\"user-menu\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"profile-img-btn\"> <!-- 이미지 버튼(회원 이미지) -->\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"profile-image\" src=\"img/");
      out.print(rs.getString("profile"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"user-menu-list\"> <!-- 메뉴리스트 -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"menu-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"menu-link\" href=\"Mypage.jsp?id=");
      out.print(rs.getString("id"));
      out.write("\"> <!-- /유저 이름으로 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"menu-icon-mini\" src=\"img/");
      out.print(rs.getString("profile"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"menu-user-name\">");
      out.print(userid );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"menu-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"menu-link\" href=\"음식바구니.jsp\" rel=\"nofollow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"menu-icon-myfood\" src=\"img/foodbox.png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"menu-text-mtfood\">내 음식바구니</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"menu-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"menu-link\"  href=\"logoutProc.jsp\" rel=\"nofollow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"menu-icon-logout\" src=\"img/logout.png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"menu-text-logout\">로그아웃</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul> <!-- user-menu-list -->\r\n");
      out.write("\t\t\t\t\t\t</div><!-- dropdown -->\r\n");
      out.write("\t\t\t\t\t</div><!-- user-menu -->\r\n");
      out.write("\t\t\t\t\t");

								} //if				
							} catch (Exception e) {
								e.printStackTrace();
							} 
						} //else
					
      out.write("\r\n");
      out.write("\t\t\t\t</div><!-- right-contents-wrapper -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"search-wrapper\">\r\n");
      out.write("\t\t\t\t\t<form class=\"search-form\" action=\"#\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t<table cellpadding=0 cellspacing=0>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<label class=\"input-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"search-keyword\" type=\"text\" name=\"keyword\" placeholder=\"검색\" required>\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"search-button\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"search.jsp\"><span class=\"ic_search\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div><!-- search-wrapper -->\t\t\t\r\n");
      out.write("\t\t</div><!-- contents-wrapper -->\r\n");
      out.write("\t\t</div><!-- main-menu -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 서브메뉴 -->\r\n");
      out.write("\t\t<div id=\"sub-menu-wrapper\" class=\"show\">\r\n");
      out.write("\t\t\t<ul class=\"sub-contents-wrapper\">\r\n");
      out.write("\t\t\t\t<li class=\"sub-menu selected\" data-text=\"인기\">\r\n");
      out.write("\t\t\t\t\t<a href=\"firstPage.jsp\">인기</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"sub-menu\" data-text=\"최신\">\r\n");
      out.write("\t\t\t\t\t<a href=\"newPost.jsp\">최신</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"sub-menu\" data-text=\"TV\">\r\n");
      out.write("\t\t\t\t\t<a href=\"whatToEat.jsp\">뭐먹지?</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"sub-menu\" data-text=\"추천\">\r\n");
      out.write("\t\t\t\t\t<a href=\"recommendTip.jsp\">추천</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul><!-- sub-contents-wrapper -->\r\n");
      out.write("\t\t</div><!-- sub-menu-wrapper -->\t\r\n");
      out.write("\t\t\r\n");
      out.write("</nav><!-- top-menu-all -->\t");
      out.write("\r\n");
      out.write("\t<!-- Center -->\r\n");
      out.write("\t\t<div class=\"center\">\r\n");
      out.write("\t\t<div class=\"toptip-wrapper\"><!-- 메인 팁 담고있는  div -->\r\n");
      out.write("\t");
   
    request.setCharacterEncoding("utf-8");
	String imgPath = null;
	
	Connection con = null;
	PreparedStatement pstmt = null;
	ResultSet rs = null;
	
	String driver = "com.mysql.jdbc.Driver";
	String url = "jdbc:mysql://localhost:3306/mucktip?serverTimezone=UTC&useSSL=false";
	String id = "root";
	String pw = "alflarhkgkrrh1!";
	

	try {
		Class.forName(driver);
		con = DriverManager.getConnection(url, id, pw);
		 
		pstmt = con.prepareStatement("select * from hotfid");
		rs = pstmt.executeQuery();
	
		if(rs.next()) {

      out.write("\r\n");
      out.write("\t\t\t<div class=\"maintip\" style=\"background-image:url('img/");
      out.print(rs.getString("img") );
      out.write("');background-size:cover;\r\n");
      out.write("\t\t\t\twidth:600px; height:600px;\">\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"maintip-inner-wrapper\" >\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"collection-information\">\r\n");
      out.write("\t\t\t\t\t<div class=\"collection-title-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"collection-title-border\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"collection-title\" style=\"overflow-wrap:break-word;\">\r\n");
      out.write("\t\t\t\t\t\t\t\"6월의 인기 음식\"<br>\"BEST 유행 음식\"</p>\r\n");
      out.write("\t\t\t\t\t\t</div><!-- collection-title-border -->\r\n");
      out.write("\t\t\t\t\t</div><!-- collection-title-wrapper -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<p class=\"collection-description-wrapper\" style=\"overflow-wrap:break-word;\">\r\n");
      out.write("\t\t\t\t\t\t\t\"핵인싸가 되고 싶다면...\"<br>\r\n");
      out.write("\t\t\t\t\t\t</p><!-- collection-description-wrapper -->\r\n");
      out.write("\t\t\t\t\t</div><!-- collection-information -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div><!-- maintip-inner-wrapper -->\r\n");
      out.write("\t\t\t  \t</div><!-- maintip -->\r\n");
      out.write("\t\t\t  \t\r\n");
      out.write("\t\t\t <div class=\"nexttip-wrapper\">\r\n");
      out.write("\t\t\t \t<div class=\"nexttip\">\r\n");
      out.write("\t\t\t \t\t");
 	
						pstmt = con.prepareStatement("select * from nexttip");
						rs = pstmt.executeQuery();
							
							if(rs.next()) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"nexttipimg\" src=\"img/");
      out.print(rs.getString("img") );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t");
 		} 
      out.write("\r\n");
      out.write("\t\t\t \t\t<div class=\"collection-information-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"collection-title-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"collection-title-border\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"collection-title-right\" style=\"overflow-wrap:break-word;\">\r\n");
      out.write("\t\t\t\t\t\t\t\"이번달 인기음식을 다 먹어봤다면?\"<br>\"이번주 음식 보러가기GG\"<br>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"go-nextpage\" href=\"nextTip.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"nextIcon\" src=\"img/nextIcon.png\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div><!-- collection-title-border -->\r\n");
      out.write("\t\t\t\t\t</div><!-- collection-title-wrapper -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div><!-- collection-information -->\r\n");
      out.write("\t\t\t \t</div><!-- nexttip -->\r\n");
      out.write("\t\t\t </div><!-- nexttip-wrapper -->\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t</div><!-- toptip-wrapper -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"maintip-feed\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"maintip-contents\" style=\"height: 1550px;\"> <!-- 전체 박스 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 첫번째 줄 -->\r\n");
      out.write("\t\t\t\t<div class=\"mucktip-card\"> <!-- 각 게시글 박스 -->\r\n");
      out.write("\t\t\t\t\t<a class=\"open-fullview\" href=\"#\">게시글</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mucktip-card\"> <!-- 각 게시글 박스 -->\r\n");
      out.write("\t\t\t\t\t게시글\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mucktip-card\"> <!-- 각 게시글 박스 -->\r\n");
      out.write("\t\t\t\t\t게시글\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mucktip-card\"> <!-- 각 게시글 박스 -->\r\n");
      out.write("\t\t\t\t\t게시글\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 두번째 줄 -->\r\n");
      out.write("\t\t\t\t<div class=\"mucktip-card\"> <!-- 각 게시글 박스 -->\r\n");
      out.write("\t\t\t\t\t게시글\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mucktip-card\"> <!-- 각 게시글 박스 -->\r\n");
      out.write("\t\t\t\t\t게시글\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mucktip-card\"> <!-- 각 게시글 박스 -->\r\n");
      out.write("\t\t\t\t\t게시글\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mucktip-card\"> <!-- 각 게시글 박스 -->\r\n");
      out.write("\t\t\t\t\t게시글\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 세번째 줄 -->\r\n");
      out.write("\t\t\t\t<div class=\"mucktip-card\"> <!-- 각 게시글 박스 -->\r\n");
      out.write("\t\t\t\t\t게시글\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mucktip-card\"> <!-- 각 게시글 박스 -->\r\n");
      out.write("\t\t\t\t\t게시글\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mucktip-card\"> <!-- 각 게시글 박스 -->\r\n");
      out.write("\t\t\t\t\t게시글\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mucktip-card\"> <!-- 각 게시글 박스 -->\r\n");
      out.write("\t\t\t\t\t게시글\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div> <!-- maintip-contents -->\t\r\n");
      out.write("\t\t</div><!-- maintip-feed -->\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div><!-- center -->\r\n");
 }catch(Exception e) {
			e.printStackTrace();
		} finally {
			try {
				if (rs != null) rs.close();
				if (pstmt != null) pstmt.close();
				if (con != null) con.close();
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}

      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		request.setCharacterEncoding("utf-8");
		String postid = request.getParameter("postid");
		String userid = (String)session.getAttribute("username");
			
		String imgPath = null;
		
		Connection con = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;
		
		String driver = "com.mysql.jdbc.Driver";
		String url = "jdbc:mysql://localhost:3306/mucktip?serverTimezone=UTC&useSSL=false";
		String id = "root";
		String pw = "alflarhkgkrrh1!";
		
		try {
			Class.forName(driver);
			con = DriverManager.getConnection(url, id, pw);
	
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>먹팁</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"fullViewStyle.css\" >\r\n");
      out.write("<script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tvar img_count = $('.content').length;\r\n");
      out.write("\t\tvar position = 1;\r\n");
      out.write("\t\t$('.prev').click(function() {\r\n");
      out.write("\t\t\tif(position > 1) {\r\n");
      out.write("\t\t\t\t$('#contents-wrapper').animate({\r\n");
      out.write("\t\t\t\t\tleft:'+=600'\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tposition--;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('.next').click(function() {\r\n");
      out.write("\t\t\tif(position < img_count) {\r\n");
      out.write("\t\t\t\t$('#contents-wrapper').animate({\r\n");
      out.write("\t\t\t\t\tleft:'-=600'\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tposition++;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction logincheck() {\r\n");
      out.write("\t\tvar login = \"");
      out.print(session.getAttribute("username"));
      out.write("\";\r\n");
      out.write("\t\tif(login == \"null\") {\r\n");
      out.write("\t\t\talert(\"로그인을 하셔야 이용할 수 있는 기능입니다.!\");\r\n");
      out.write("\t\t\tlocation.href = \"login.jsp\";\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t\t\tlocation.href = \"likeAction.jsp?userid=");
      out.print(userid);
      out.write("&postid=");
      out.print(postid);
      out.write("\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction enterkey() {\r\n");
      out.write("\t\tif(window.event.keyCode == 13) { //엔터키가 눌렸을 때 실행\r\n");
      out.write("\t\t\tvar comment = null;\r\n");
      out.write("\t\t\tcomment = document.getElementById(\"comment\").value;\r\n");
      out.write("\t\t\tif(comment != \"\\n\") {\r\n");
      out.write("\t\t\t\tlocation.href = \"commentAction.jsp?comment=\"+comment+\"&userid=");
      out.print(userid);
      out.write("&postid=");
      out.print(postid);
      out.write("\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(\"comment\").value = null; //값 초기화\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction delOk(id) {\r\n");
      out.write("\t\tvar del = confirm(\"댓글을 삭제하시겠습니까?\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(del){\r\n");
      out.write("\t\t\tlocation.href = \"commentDel.jsp?id=\"+id+\"&postid=");
      out.print(postid);
      out.write("\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "TopWrapper.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- <div id=\"dim-layer\" class=\"hidden\"> -->\r\n");
      out.write("<!-- <div class=\"mask\"></div> -->\r\n");
      out.write("<!-- <div class=\"muktip-modal\"> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t<div class=\"tip-position\"> -->\r\n");
      out.write("<!-- \t<div class=\"middle\"> -->\r\n");
      out.write("<!-- \t<div class=\"tip-frame\"> -->\r\n");
      out.write("<!-- \t<div class=\"tip-body\"> -->\r\n");
      out.write("<!-- \t<div class=\"top-upper-body\"> -->\r\n");
      out.write("<!-- \t\t<div class=\"close\"><a class=\"close-fullview\" href=\"#stay\">X</a></div>   -->\r\n");
      out.write("\t<section class=\"fullview\">\r\n");
      out.write("\t\t\t\t<div class=\"fullview-inner-wrapper\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"pictures-wrapper\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pictures\" data-contents-count=\"DB count\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"conveyer-belt\" data-picture-ids=\"DB picture ID\">\r\n");
      out.write("\t\t\t\t\t\t\t<figure id=\"contents-wrapper\" class=\"img-contents-wrapper\" style=\"width:1800px; height: 600px;\">\r\n");
      out.write("\t");
		
			pstmt = con.prepareStatement("select * from img where postimgid = ?");
			pstmt.setString(1, postid);
			rs = pstmt.executeQuery();
	
			while(rs.next()) {    
				imgPath =request.getContextPath() + "/post/" + rs.getString("imgname");
	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"content\" src=\"");
      out.print( imgPath );
      out.write("\" data-mobile-src=\"address\" width=\"600\" height=\"600\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-latio=\"1.0\" data-picture-id=\"DB id\">\r\n");
      out.write("\t");
		
			}
	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</figure>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div><!-- conveyer-belt -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<button class=\"prev\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sprit arrow-left\"><img src=\"img/prev.png\" width=50px height=50px></span>\r\n");
      out.write("\t\t\t\t\t\t</button><!-- prev -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<button class=\"next\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sprit arrow-right\"><img src=\"img/next.png\" width=50px height=50px></span>\t\t\r\n");
      out.write("\t\t\t\t\t\t</button><!-- next -->\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div><!-- pictures -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"sumnails-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sumnails\">\r\n");
      out.write("\t");

			pstmt = con.prepareStatement("select * from img where postimgid = ?");
			pstmt.setString(1, postid);
			rs = pstmt.executeQuery();
			
			while(rs.next()) {   
				imgPath =request.getContextPath() + "/post/" + rs.getString("imgname");
	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<figure class=\"sumnail-border\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"sumnail\" src=\"");
      out.print( imgPath );
      out.write("\" width=\"50\" height=\"50\">\r\n");
      out.write("\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t");

			}
	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div><!-- sumnails -->\r\n");
      out.write("\t\t\t\t\t</div><!-- sumnails-wrapper -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div><!-- pictures-wrapper -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t");

			pstmt = con.prepareStatement("select distinct postid, postimgid, title, content, writer, date, imgname, id, profile from post join img on postid = postimgid join user on writer = id where postid=? group by postid;");
			pstmt.setString(1, postid);
			rs = pstmt.executeQuery();
	
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"side-position\" id=\"error_solve\">\r\n");
      out.write("\t\t\t\t\t<div class=\"information-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"information\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"user-card\" data-following-status-url=\"게시자 링크\">\r\n");
      out.write("\t");
		
			if(rs.next()) {
	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"profile-picture\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a hrf=\"Mypage.jsp?id=");
      out.print(rs.getString("id"));
      out.write("\" target=\"_blank\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"user-profile\" src=\"img/");
      out.print(rs.getString("profile") );
      out.write("\" width=\"40px\" height=\"40px\"> <!-- img(user) in DB -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div><!-- profile-picture -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"user-information\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"nickname\" href=\"유저 아이디\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"name-bold\">");
      out.print(rs.getString("writer"));
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div><!-- clearfix -->\r\n");
      out.write("\t\t\t\t\t\t\t</div><!-- user-information -->\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div><!-- user-card -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"scroll-bar-component\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"description-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"title-wrapper\">");
      out.print(rs.getString("title") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"content-wrapper\">");
      out.print(rs.getString("content") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div><!-- discription-wrapper -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"scroll-bar-rail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"bar\" style=\"margin-top:0px; height: 120px;\"></div><!-- bar -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div><!-- scroll-bar-rail -->\r\n");
      out.write("\t");
			
			}
	
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div><!-- scroll-bar-component -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div><!-- information -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"action\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<button class=\"like-btn\" onclick=\"logincheck()\">\r\n");
      out.write("\t");

			pstmt = con.prepareStatement("select * from goodmuck where userid=? and postid=?");
			pstmt.setString(1, userid);
			pstmt.setString(2, postid);
			rs = pstmt.executeQuery();
			if(rs.next()) {
				int goodchk = rs.getInt("good_chk");
				if(goodchk == 1) {
					out.println("<img class='like-img' src='img/spoon2.png'>");
				} else {
					out.println("<img class='like-img' src='img/spoon1.png'>");
				}
			} else {
				out.println("<img class='like-img' src='img/spoon1.png'>");
			} 
			
			pstmt = con.prepareStatement("select count(*) from goodmuck where postid=? and good_chk=?");
			pstmt.setString(1, postid);
			pstmt.setInt(2, 1);
			rs = pstmt.executeQuery();
			
			int likecount = 0;
			if(rs.next()) {
				likecount = rs.getInt(1);			
			}
	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"like-count\">");
      out.print( likecount );
      out.write("</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div><!-- action -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div><!-- information-position -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"comment-wrapper\" data-comments-url=\"디비주소\" data-comments-count=\"DB comments count\">\r\n");
      out.write("\t");

			pstmt = con.prepareStatement("select * from comments where postid=?");
			pstmt.setString(1, postid);
			rs = pstmt.executeQuery();
			
			if(rs.next()) {
				pstmt = con.prepareStatement("select count(*) from comments where postid=?");
				pstmt.setString(1, postid);
				rs = pstmt.executeQuery();
				
				if(rs.next()) {
	
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear-fix\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"comments-count\">댓글\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"op-count\">(");
      out.print(rs.getInt(1));
      out.write(")</span>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div><!-- clear-fix -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"comments\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"comments-inner-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"op-comments\">\r\n");
      out.write("\t");

				}
				
				pstmt = con.prepareStatement("select commentsid, comment, date, id, profile from comments join user on userid = id where postid=?");
				pstmt.setString(1, postid);
				rs = pstmt.executeQuery();
				
				while(rs.next()) {
	
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<button class=\"load-comments\" data-next-url=\"(디비에 있는 주소)\">더 보기 -->\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"comment\" data-id=\"id\" data-autor-id=\"id\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-author-bio data-author-nickname=\"댓글 단 user닉네임\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-author-profile-picture-url=\"사진 누르면 댓글단 user페이지로\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"commenter-picture\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"Mypage.jsp?id=");
      out.print(rs.getString("id"));
      out.write("\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"img/");
      out.print(rs.getString("profile") );
      out.write("\" width=\"30\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div><!-- commenter-picture-left -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"delete-button-wrapper\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"remaining-width\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"comment-body-wrapper remaining-width\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"commenter\" href=\"Mypage.jsp?id=");
      out.print(rs.getString("id"));
      out.write("\" target=\"_blank\">");
      out.print(rs.getString("id") );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"comment-body\">");
      out.print(rs.getString("comment") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<time datetime=\"댓글단 날짜\" title=\"댓글쓴날짜\">");
      out.print(rs.getDate("date") );
      out.write("</time>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div><!-- remaining-width -->\r\n");
      out.write("\t");

					if(userid.equals(rs.getString("id"))) { //내가 쓴 댓글만 삭제 가능
	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"del-button-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"del-button\" onclick=\"delOk(");
      out.print(rs.getInt("commentsid"));
      out.write(")\">X</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</li><!-- comment -->\r\n");
      out.write("\t");
		
					}
				}
	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul><!-- op-comments -->\r\n");
      out.write("\t\t\t\t\t</div><!-- comments-inner-wrapper -->\r\n");
      out.write("\t");

			} else { 
	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear-fix\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"comments-count\">댓글\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"op-count\">(0)</span>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div><!-- clear-fix -->\t\r\n");
      out.write("\t");

			}
			
			if(userid != null) {
	
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"comment-input-field\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"mentionable-users\"></ul>\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"side-input-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea type=\"text\" class=\"input\" id=\"comment\" placeholder=\"댓글을 남기세요,,,\" tabindex=\"1\" onkeyup=\"enterkey();\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div><!-- input-wrapper -->\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</div><!-- comment-input-field -->\r\n");
      out.write("\t");

			}
	
      out.write("\r\n");
      out.write("\t\t\t\t\t</div><!-- comment-wrapper -->\r\n");
      out.write("\t\t\t\t</div><!-- side-position -->\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</div><!-- fullview-inner-wrapper -->\r\n");
      out.write("\t\t</section><!-- fillview -->\r\n");
      out.write("\t\t\r\n");

 		} catch (Exception e) {
 			e.printStackTrace();
 		} finally {
 			try {
 				if (rs != null) rs.close();
 				if (pstmt != null) pstmt.close();
 				if (con != null) con.close();
 			} catch (SQLException e) {
 				e.printStackTrace();
 			}
 		}
		

      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("<!-- \t</div>top-upper-body -->\r\n");
      out.write("<!-- \t</div>tip-body -->\r\n");
      out.write("<!-- \t</div>tip-frame -->\r\n");
      out.write("<!-- \t</div>middle -->\r\n");
      out.write("<!-- \t</div>tip-position -->\r\n");
      out.write("\r\n");
      out.write("<!-- </div>dim-layer  -->\r\n");
      out.write("<!-- </div>muktip-modal -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"footerStyle.css\" >\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<div class=\"footer-wrqpper\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"first-wrapper\">\r\n");
      out.write("\t\t\t<img src=\"img/title.png\" width=\"200\" height=\"130\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- first-wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"second-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"developer-information-wrapper\">\r\n");
      out.write("\t\t\t\t<p class=\"developer\">개발자</p>\r\n");
      out.write("\t\t\t\t<!-- 이 글자가 우리 둘 정보의 위의 가운데에 배치 -->\r\n");
      out.write("\t\t\t\t<div class=\"left-developer\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"developer-name\">이규빈(Lee KyuBeen)</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"developer-tel\">tel:010-9067-0353</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"developer-email\">s2017i34@e-mirim.hs.kr</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- left-developer -->\r\n");
      out.write("\t\t\t\t<div class=\"right-developer\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"developer-name\">박혜정(Park HyeJung)</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"developer-tel\">tel:010-7335-3662</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"developer-email\">s2017i27@e-mirim.hs.kr</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- right-developer -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- developer-information-wrapper -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- second-wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"third-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"designer-information-wrapper\">\r\n");
      out.write("\t\t\t\t<p class=\"designer\">디자이너</p>\r\n");
      out.write("\t\t\t\t<div class=\"first-designer\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"developer-name\">서지인(Seo JiIn)</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"developer-tel\">tel:010-2565-5186</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"developer-email\">s2017i28@e-mirim.hs.kr</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div> <!-- first-designer -->\r\n");
      out.write("\t\t\t</div> <!-- designer-information-wrapper  -->\r\n");
      out.write("\t\t</div><!-- third-wrapper -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div><!-- footer-wrapper -->\r\n");
      out.write("\t\r\n");
      out.write("</div> <!-- footer -->");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
