/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.5
 * Generated at: 2019-05-30 14:10:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class souvenirProc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"souvenirStyle.css\" >\r\n");
      out.write("<title>Souvenir</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            $(document).ready(function() {\r\n");
      out.write("                  \r\n");
      out.write("                var xOffset = 10;\r\n");
      out.write("                var yOffset = 30;\r\n");
      out.write(" \r\n");
      out.write("                $(document).on(\"mouseover\",\"#thumbnail\",function(e){ //마우스 오버시\r\n");
      out.write("                     \r\n");
      out.write("                    $(\"body\").append(\"<p id='preview'><img src='\"+ $(this).attr(\"src\") +\"' width='400px' /></p>\"); //보여줄 이미지를 선언                       \r\n");
      out.write("                    $(\"#preview\")\r\n");
      out.write("                        .css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("                        .css(\"left\",(e.pageX + yOffset) + \"px\")\r\n");
      out.write("                        .fadeIn(\"fast\"); //미리보기 화면 설정 셋팅\r\n");
      out.write("                });\r\n");
      out.write("                 \r\n");
      out.write("                $(document).on(\"mousemove\",\"#thumbnail\",function(e){ //마우스 이동시\r\n");
      out.write("                    $(\"#preview\")\r\n");
      out.write("                        .css(\"top\",(e.pageY - xOffset) + \"px\")\r\n");
      out.write("                        .css(\"left\",(e.pageX + yOffset) + \"px\");\r\n");
      out.write("                });\r\n");
      out.write("                 \r\n");
      out.write("                $(document).on(\"mouseout\",\"#thumbnail\",function(){ //마우스 아웃시\r\n");
      out.write("                    $(\"#preview\").remove();\r\n");
      out.write("                });\r\n");
      out.write("                  \r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("             \r\n");
      out.write("        <style>\r\n");
      out.write("            /* 미리보기 스타일 셋팅 */\r\n");
      out.write("            #preview{\r\n");
      out.write("                z-index: 9999;\r\n");
      out.write("                position:absolute;\r\n");
      out.write("                border:0px solid #ccc;\r\n");
      out.write("                background:#333;\r\n");
      out.write("                padding:1px;\r\n");
      out.write("                display:none;\r\n");
      out.write("                color:#fff;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"souvenir-wrapper\">\r\n");
      out.write("\t<p class=\"souvenir\"><b>Souvenir</b></p>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<h2 class=\"summer\">Summer</h2><p class=\"dollar\">- $29.95</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div onclick=\"imgbigview('img/ms1PNG','bigimg'); return false;\">\r\n");
      out.write("\t\t<img src=\"img/ms1.PNG\" class=\"ms1\" id=\"thumbnail\">\r\n");
      out.write("\t\t<h4 class=\"ms_1\">Short T-shirt</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<hr style=\"\tleft:480px; top:480px;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h2 class=\"winter\">Winter</h2><p class=\"dollar2\">- $49.95</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div onclick=\"imgbigview('img/ms3.PNG','bigimg'); return false;\">\r\n");
      out.write("\t\t<img src=\"img/ms3.PNG\" class=\"ms3\" id=\"thumbnail\">\r\n");
      out.write("\t\t<h4 class=\"ms_3\">Slytherin Hoodie</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t<div onclick=\"imgbigview('img/ms4.PNG','bigimg'); return false;\">\r\n");
      out.write("\t\t<img src=\"img/ms4.PNG\" class=\"ms4\" id=\"thumbnail\">\r\n");
      out.write("\t\t<h4 class=\"ms_4\">Hufflepuff Hoodie</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div onclick=\"imgbigview('img/ms5.PNG','bigimg'); return false;\">\r\n");
      out.write("\t\t<img src=\"img/ms5.PNG\" class=\"ms5\" id=\"thumbnail\">\r\n");
      out.write("\t\t<h4 class=\"ms_5\">Gryfindor Hoodie</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div onclick=\"imgbigview('img/ms6.PNG','bigimg'); return false;\">\r\n");
      out.write("\t\t<img src=\"img/ms6.PNG\" class=\"ms6\" id=\"thumbnail\">\r\n");
      out.write("\t\t<h4 class=\"ms_6\">Ravenclaw Hoodie</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div onclick=\"imgbigview('img/ms7.PNG','bigimg'); return false;\">\r\n");
      out.write("\t\t<img src=\"img/ms7.PNG\" class=\"ms7\" id=\"thumbnail\">\r\n");
      out.write("\t\t<h4 class=\"ms_7\">Hogwarts Hoodie</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<hr style=\"\tleft:480px; top:1350px;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h2 class=\"cup\">Cup</h2><p class=\"dollar3\">- $14.41</p>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div onclick=\"imgbigview('img/ms8.PNG','bigimg'); return false;\">\r\n");
      out.write("\t\t<img src=\"img/ms8.PNG\" class=\"ms8\" id=\"thumbnail\">\r\n");
      out.write("\t\t<h4 class=\"ms_8\">Hufflepuff Cup</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div onclick=\"imgbigview('img/ms9.PNG','bigimg'); return false;\">\r\n");
      out.write("\t\t<img src=\"img/ms9.PNG\" class=\"ms9\" id=\"thumbnail\">\r\n");
      out.write("\t\t<h4 class=\"ms_9\">Slytherin Cup</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div onclick=\"imgbigview('img/ms10.PNG','bigimg'); return false;\">\r\n");
      out.write("\t\t<img src=\"img/ms10.PNG\" class=\"ms10\" id=\"thumbnail\">\r\n");
      out.write("\t\t<h4 class=\"ms_10\">Ravenclaw Cup</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div onclick=\"imgbigview('img/ms11.PNG','bigimg'); return false;\">\r\n");
      out.write("\t\t<img src=\"img/ms11.PNG\" class=\"ms11\" id=\"thumbnail\">\r\n");
      out.write("\t\t<h4 class=\"ms_11\">Gryfindor Cup</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<hr style=\"\tleft:480px; top:2200px;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h2 class=\"etc\">ETC</h2><p class=\"dollar4\">- $25.46</p>\r\n");
      out.write("\t\t<div onclick=\"imgbigview('img/ms2PNG','bigimg'); return false;\">\r\n");
      out.write("\t\t<img src=\"img/ms2.PNG\" class=\"ms2\" id=\"thumbnail\">\r\n");
      out.write("\t\t<h4 class=\"ms_2\">Magic House Hat</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- 상세이미지 보여주는 공간 \r\n");
      out.write("\t<div id=\"bigimg\" style=\"display:none;\">\r\n");
      out.write("\t<img src=\"\" onclick=\"hide('bigimg')\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t-->\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
